//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class ARRIENDO
    {
        public int Codigo_Transaccion { get; set; }
        public System.DateTime Fecha_Inicio_Contrato { get; set; }
        public System.DateTime Fecha_Fin_Contrato { get; set; }
        public int Duracion_Contrato_Meses { get; set; }

        [JsonIgnore]
        public virtual TRANSACCION TRANSACCION { get; set; }
    }
}
