//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.FACTURAs = new HashSet<FACTURA>();
            this.TRANSACCIONs = new HashSet<TRANSACCION>();
            this.VISITAs = new HashSet<VISITA>();
        }
    
        public int Codigo_Cliente { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> Tipo_Doc { get; set; }
        public string Nro_Documento { get; set; }
        public Nullable<int> Tipo_Telefono { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Codigo_Ciudad { get; set; }
        public int Codigo_Genero { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
    
        [JsonIgnore]
        public virtual CIUDAD CIUDAD { get; set; }
        [JsonIgnore]
        public virtual GENERO GENERO { get; set; }
        [JsonIgnore]
        public virtual TIPO_DOCUMENTO TIPO_DOCUMENTO { get; set; }
        [JsonIgnore]
        public virtual TIPO_TELEFONO TIPO_TELEFONO1 { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURAs { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACCION> TRANSACCIONs { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VISITA> VISITAs { get; set; }
    }
}
