//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA_PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPRA_PROVEEDOR()
        {
            this.DETALLE_COMPRA_PROVEEDOR = new HashSet<DETALLE_COMPRA_PROVEEDOR>();
        }
    
        public int Codigo_Compra { get; set; }
        public int Codigo_Proveedor { get; set; }
        public System.DateTime Fecha_Compra { get; set; }
        public decimal Monto_Total { get; set; }
        public string Descripcion { get; set; }
        public int Codigo_Empleado { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_COMPRA_PROVEEDOR> DETALLE_COMPRA_PROVEEDOR { get; set; }
    }
}
