//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBINMOBILIARIAEntities : DbContext
    {
        public DBINMOBILIARIAEntities()
            : base("name=DBINMOBILIARIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARRIENDO> ARRIENDOes { get; set; }
        public virtual DbSet<CIUDAD> CIUDADs { get; set; }
        public virtual DbSet<CLIENTE> CLIENTEs { get; set; }
        public virtual DbSet<COMPRA_PROVEEDOR> COMPRA_PROVEEDOR { get; set; }
        public virtual DbSet<DECORACION_MODELO> DECORACION_MODELO { get; set; }
        public virtual DbSet<DETALLE_COMPRA_PROVEEDOR> DETALLE_COMPRA_PROVEEDOR { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOes { get; set; }
        public virtual DbSet<FACTURA> FACTURAs { get; set; }
        public virtual DbSet<FORMA_PAGO> FORMA_PAGO { get; set; }
        public virtual DbSet<GENERO> GENEROes { get; set; }
        public virtual DbSet<INMUEBLE> INMUEBLEs { get; set; }
        public virtual DbSet<INMUEBLE_CONSIGNACION> INMUEBLE_CONSIGNACION { get; set; }
        public virtual DbSet<PERFIL> PERFILs { get; set; }
        public virtual DbSet<PERFIL_USUARIO> PERFIL_USUARIO { get; set; }
        public virtual DbSet<PRODUCTO_SERVICIO_PROVEEDOR> PRODUCTO_SERVICIO_PROVEEDOR { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDORs { get; set; }
        public virtual DbSet<PROYECTO_NUEVO> PROYECTO_NUEVO { get; set; }
        public virtual DbSet<SEDE> SEDEs { get; set; }
        public virtual DbSet<TIPO_DOCUMENTO> TIPO_DOCUMENTO { get; set; }
        public virtual DbSet<TIPO_EMPLEADO> TIPO_EMPLEADO { get; set; }
        public virtual DbSet<TIPO_INMUEBLE> TIPO_INMUEBLE { get; set; }
        public virtual DbSet<TIPO_PAGO> TIPO_PAGO { get; set; }
        public virtual DbSet<TIPO_TELEFONO> TIPO_TELEFONO { get; set; }
        public virtual DbSet<TIPO_TRANSACCION> TIPO_TRANSACCION { get; set; }
        public virtual DbSet<TRANSACCION> TRANSACCIONs { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
        public virtual DbSet<VENTA> VENTAs { get; set; }
        public virtual DbSet<VISITA> VISITAs { get; set; }
        public virtual DbSet<IMAGEN_INMUEBLE> IMAGEN_INMUEBLE { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTOes { get; set; }
        public virtual DbSet<ESTADO> ESTADOes { get; set; }
        public virtual DbSet<ESTADO_PAGO> ESTADO_PAGO { get; set; }
    }
}
