//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_COMPRA_PROVEEDOR
    {
        public int Detalle_ID { get; set; }
        public int Codigo_Compra { get; set; }
        public int Codigo_Producto { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio_Unitario { get; set; }

        [JsonIgnore]
        public virtual COMPRA_PROVEEDOR COMPRA_PROVEEDOR { get; set; }
        [JsonIgnore]
        public virtual PRODUCTO_SERVICIO_PROVEEDOR PRODUCTO_SERVICIO_PROVEEDOR { get; set; }
    }
}
