//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLEADO()
        {
            this.COMPRA_PROVEEDOR = new HashSet<COMPRA_PROVEEDOR>();
            this.DECORACION_MODELO = new HashSet<DECORACION_MODELO>();
            this.FACTURAs = new HashSet<FACTURA>();
            this.INMUEBLEs = new HashSet<INMUEBLE>();
            this.TRANSACCIONs = new HashSet<TRANSACCION>();
            this.USUARIOs = new HashSet<USUARIO>();
            this.VISITAs = new HashSet<VISITA>();
        }
    
        public int Codigo_Empleado { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> Tipo_Doc { get; set; }
        public string Nro_Documento { get; set; }
        public Nullable<int> Tipo_Telefono { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public System.DateTime Fecha_Contratacion { get; set; }
        public int Codigo_TipoEmpleado { get; set; }
        public int Codigo_Sede { get; set; }
        public int Codigo_Genero { get; set; }

        [JsonIgnore]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA_PROVEEDOR> COMPRA_PROVEEDOR { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECORACION_MODELO> DECORACION_MODELO { get; set; }
        [JsonIgnore]
        public virtual TIPO_EMPLEADO TIPO_EMPLEADO { get; set; }
        [JsonIgnore]
        public virtual SEDE SEDE { get; set; }
        [JsonIgnore]
        public virtual GENERO GENERO { get; set; }
        [JsonIgnore]
        public virtual TIPO_DOCUMENTO TIPO_DOCUMENTO { get; set; }
        [JsonIgnore]
        public virtual TIPO_TELEFONO TIPO_TELEFONO1 { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURAs { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INMUEBLE> INMUEBLEs { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACCION> TRANSACCIONs { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO> USUARIOs { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VISITA> VISITAs { get; set; }
    }
}
