//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        public int Codigo_Factura { get; set; }
        public int Codigo_Transaccion { get; set; }
        public int Codigo_Cliente { get; set; }
        public int Codigo_Inmueble { get; set; }
        public Nullable<int> Codigo_Empleado_Genera { get; set; }
        public int Codigo_Forma { get; set; }
        public System.DateTime Fecha_Emision { get; set; }
        public Nullable<System.DateTime> Fecha_Vencimiento { get; set; }
        public decimal Monto_Total { get; set; }
        public string Concepto { get; set; }
        public Nullable<System.DateTime> Fecha_Pago { get; set; }
        public string Notas_Factura { get; set; }
        public int Codigo_EstadoPago { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual TRANSACCION TRANSACCION { get; set; }
        public virtual INMUEBLE INMUEBLE { get; set; }
        public virtual FORMA_PAGO FORMA_PAGO { get; set; }
        public virtual ESTADO_PAGO ESTADO_PAGO { get; set; }
    }
}
