//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGEN_INMUEBLE
    {
        public int Codigo_Imagen { get; set; }
        public int Codigo_Inmueble { get; set; }
        public string Url_Imagen { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Es_Principal { get; set; }
        public Nullable<System.DateTime> Fecha_Subida { get; set; }

        [JsonIgnore]
        public virtual INMUEBLE INMUEBLE { get; set; }
    }
}
