//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class INMUEBLE_CONSIGNACION
    {
        public int Codigo_Inmueble { get; set; }
        public string Nombre_Propietario { get; set; }
        public string Telefono_Propietario { get; set; }
        public string Email_Propietario { get; set; }
    
        [JsonIgnore]
        public virtual INMUEBLE INMUEBLE { get; set; }
    }
}
