//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaAPI.Models
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    public partial class INMUEBLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INMUEBLE()
        {
            this.FACTURAs = new HashSet<FACTURA>();
            this.TRANSACCIONs = new HashSet<TRANSACCION>();
            this.VISITAs = new HashSet<VISITA>();
            this.DECORACION_MODELO = new HashSet<DECORACION_MODELO>();
            this.PROYECTO_NUEVO = new HashSet<PROYECTO_NUEVO>();
            this.IMAGEN_INMUEBLE = new HashSet<IMAGEN_INMUEBLE>();
        }
    
        public int Codigo_Inmueble { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Direccion { get; set; }
        public int Codigo_Ciudad { get; set; }
        public int Codigo_TipoInmueble { get; set; }
        public bool Es_Nuevo { get; set; }
        public System.DateTime Fecha_Alta { get; set; }
        public string Descripcion { get; set; }
        public int Codigo_Empleado_Captacion { get; set; }
        public Nullable<decimal> Precio_Venta { get; set; }
        public Nullable<decimal> Canon_Mensual { get; set; }
        public Nullable<decimal> Metros_Cuadrados { get; set; }
        public Nullable<int> Numero_Habitaciones { get; set; }
        public Nullable<int> Numero_Banos { get; set; }
        public Nullable<int> Estrato { get; set; }
        public Nullable<bool> Tiene_Parqueadero { get; set; }
        public Nullable<int> Numero_Pisos { get; set; }
        public Nullable<int> Anio_Construccion { get; set; }
        public int Codigo_Estado { get; set; }

        [JsonIgnore]
        public virtual CIUDAD CIUDAD { get; set; }
        [JsonIgnore]
        public virtual EMPLEADO EMPLEADO { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURAs { get; set; }
        [JsonIgnore]
        public virtual INMUEBLE_CONSIGNACION INMUEBLE_CONSIGNACION { get; set; }
        [JsonIgnore]
        public virtual TIPO_INMUEBLE TIPO_INMUEBLE { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACCION> TRANSACCIONs { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VISITA> VISITAs { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DECORACION_MODELO> DECORACION_MODELO { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROYECTO_NUEVO> PROYECTO_NUEVO { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGEN_INMUEBLE> IMAGEN_INMUEBLE { get; set; }
        [JsonIgnore]
        public virtual ESTADO ESTADO { get; set; }
    }
}
