//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PERFIL_USUARIO
    {
        public int Codigo { get; set; }
        public int Codigo_Usuario { get; set; }
        public int Codigo_Perfil { get; set; }
        public bool Activo { get; set; }

        [JsonIgnore]
        public virtual PERFIL PERFIL { get; set; }
        [JsonIgnore]
        public virtual USUARIO USUARIO { get; set; }
    }
}
