//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_SERVICIO_PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO_SERVICIO_PROVEEDOR()
        {
            this.DETALLE_COMPRA_PROVEEDOR = new HashSet<DETALLE_COMPRA_PROVEEDOR>();
        }
    
        public int Codigo_Producto { get; set; }
        public int Codigo_Proveedor { get; set; }
        public string Nombre_Producto { get; set; }
        public string Unidad_Medida { get; set; }
        public decimal Precio_Unitario { get; set; }
    
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_COMPRA_PROVEEDOR> DETALLE_COMPRA_PROVEEDOR { get; set; }
        [JsonIgnore]
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
