//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDOR()
        {
            this.COMPRA_PROVEEDOR = new HashSet<COMPRA_PROVEEDOR>();
            this.PRODUCTO_SERVICIO_PROVEEDOR = new HashSet<PRODUCTO_SERVICIO_PROVEEDOR>();
        }
    
        public int Codigo_Proveedor { get; set; }
        public string Nombre_Proveedor { get; set; }
        public string Nombre_Contacto { get; set; }
        public Nullable<int> Tipo_Telefono { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Direccion { get; set; }
        [JsonIgnore]
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA_PROVEEDOR> COMPRA_PROVEEDOR { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO_SERVICIO_PROVEEDOR> PRODUCTO_SERVICIO_PROVEEDOR { get; set; }
        [JsonIgnore]
        public virtual TIPO_TELEFONO TIPO_TELEFONO1 { get; set; }
    }
}
