//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PROYECTO_NUEVO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROYECTO_NUEVO()
        {
            this.INMUEBLEs = new HashSet<INMUEBLE>();
        }
    
        public int Codigo_Proyecto { get; set; }
        public string Nombre_Proyecto { get; set; }
        public string Direccion { get; set; }
        public int Codigo_Ciudad { get; set; }
    
        [JsonIgnore]
        public virtual CIUDAD CIUDAD { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INMUEBLE> INMUEBLEs { get; set; }
    }
}
