//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSACCION()
        {
            this.FACTURAs = new HashSet<FACTURA>();
        }
    
        public int Codigo_Transaccion { get; set; }
        public int Codigo_Inmueble { get; set; }
        public int Codigo_Cliente { get; set; }
        public int Codigo_Empleado_Cierre { get; set; }
        public int Codigo_TipoTransaccion { get; set; }
        public System.DateTime Fecha_Transaccion { get; set; }
        public decimal Precio_Acordado { get; set; }
        public string Notas_Transaccion { get; set; }
    
        public virtual ARRIENDO ARRIENDO { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURAs { get; set; }
        public virtual INMUEBLE INMUEBLE { get; set; }
        public virtual TIPO_TRANSACCION TIPO_TRANSACCION { get; set; }
        public virtual VENTA VENTA { get; set; }
    }
}
