//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.PERFIL_USUARIO = new HashSet<PERFIL_USUARIO>();
        }
    
        public int Codigo_Usuario { get; set; }
        public Nullable<int> Documento_Empleado { get; set; }
        public string Username { get; set; }
        public string Clave { get; set; }
        public string Salt { get; set; }

        [JsonIgnore]
        public virtual EMPLEADO EMPLEADO { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERFIL_USUARIO> PERFIL_USUARIO { get; set; }
    }
}
