//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InmobiliariaAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class VISITA
    {
        public int Codigo_Visita { get; set; }
        public int Codigo_Inmueble { get; set; }
        public int Codigo_Cliente { get; set; }
        public System.DateTime Fecha_Visita { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> Codigo_Empleado { get; set; }
    
        [JsonIgnore]
        public virtual CLIENTE CLIENTE { get; set; }
        [JsonIgnore]
        public virtual EMPLEADO EMPLEADO { get; set; }
        [JsonIgnore]
        public virtual INMUEBLE INMUEBLE { get; set; }
    }
}
